[Bug 906500 - quartz throwing NoClassDefFoundError: oracle/sql/BLOB] I believe this is fixed.  I added an optional module dependency on the Oracle driver, for the server jar.  Our datasources had no problem, they are defined correctly to find/use the oracle driver, but since Quartz wants to perform a test directly against a driver class, we had to ensure the driver jar was accessible to the classloader.