Bug 855926 - Apache plug-in throws NoClassDefFoundError or UnsatisfiedLinkError when Augeas is enabled but library can not be read
Log meaningful messages on failure to find/link Augeas lib

Catch NoClassDefFoundError and UnsatisfiedLinkError and report them
appropriately when checking for presence of Augeas in Apache plugin.

Also emit slightly more direct message if we do not support Augeas for
given version of Apache.

(cherry picked from commit f7f0011072dd56f1a081aa24351966656ff94f83)
Signed-off-by: Thomas Segismont <tsegismo@redhat.com>