Guarding against hibernate exception that can occur when using delete-orphan
While adding/updating tests I was running into,

HibernateException: A collection with cascade="all-delete-orphan" was no longer
referenced by the owning entity instance

The solution is to make sure that the managed collection references do
not change